### ISSUE TITLE
cap.jpeg instead of cap.jpg?

### ISSUE THREAD

**Issue by cezar-c** [githubdoe/skysolve#5]
Hi,

First, I would like to thank you for your code. Because of it, I bought a RPI5, a HQ camera and 16mm objective lens. All together work perfectly.
Is it possible that in newCamLib branch, in skysolve.py at line 316, to have 'cap.jpeg' instead of 'cap.jpg'?

Best regards,
Cezar

**Comment by githubdoe** [comment]
I'm in the middle of modifying several things in the source.  So just hold on.  It may take me a few days.  Part of the change is to change all .jpeg extensions to ".jpg".  So the quick answer is no.  I will announce on github when it is ready.

Dale

**Comment by githubdoe** [comment]
I just pushed what I think works.  You can try it if you want.  It probably needs more debugging.   For instance it has not been tired out under the stars.
 
I have not tried a fresh pull of the code so there is a chance I left something out.

**Comment by cezar-c** [comment]
Thank you. 
I will give it a try.

**Comment by githubdoe** [comment]
Tested under the stars tonight.  It works but I made some improvements like removing unneeded print statments and mods to help status message of found stars display longer.
Code pushed to branch.
